# Generated by Django 5.1.8 on 2025-04-17 07:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='preview',
            new_name='can_preview',
        ),
        migrations.AddField(
            model_name='lesson',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
    ]
