# Generated by Django 5.1.8 on 2025-05-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='emailverificationevent',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
